# Book Recommendation Engine using KNN
This is my solution for the Book Recommendation Engine using KNN project from FreeCodeCamp. Instructions for this project can be found [here](https://www.freecodecamp.org/learn/machine-learning-with-python/machine-learning-with-python-projects/book-recommendation-engine-using-knn).

## Introduction
This challenge is harder than it looks. It requires studying additional learning resources. Setting up KNN itself is easy but involves tricky data preprocessing. The short answer is pivot tables.

In [ ]:
# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [ ]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

--2023-08-15 14:29:22--  https://cdn.freecodecamp.org/project-data/books/book-crossings.zip
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 104.26.2.33, 104.26.3.33, 172.67.70.149, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|104.26.2.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26085508 (25M) [application/zip]
Saving to: ‘book-crossings.zip’

book-crossings.zip  100%[===================>]  24.88M  --.-KB/s    in 0.1s    

2023-08-15 14:29:22 (168 MB/s) - ‘book-crossings.zip’ saved [26085508/26085508]

Archive:  book-crossings.zip
  inflating: BX-Book-Ratings.csv     
  inflating: BX-Books.csv            
  inflating: BX-Users.csv            


In [ ]:
# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

In [ ]:
# Check the books dataset
df_books.head()

isbn                                              title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

                 author  
0    Mark P. O. Morford  
1  Richard Bruce Wright  
2          Carlo D'Este  
3      Gina Bari Kolata  
4       E. J. W. Barber

In [ ]:
df_books.shape

(271379, 3)

In [ ]:
df_books.isnull().sum()

isbn      0
title     0
author    1
dtype: int64

In [ ]:
# Drop NaN values from the books dataset
df_books.dropna(inplace=True)
df_books.shape

(271378, 3)

In [ ]:
# Check the ratings dataset
df_ratings.head()

user        isbn  rating
0  276725  034545104X     0.0
1  276726  0155061224     5.0
2  276727  0446520802     0.0
3  276729  052165615X     3.0
4  276729  0521795028     6.0

In [ ]:
df_ratings.shape

(1149780, 3)

In [ ]:
df_ratings.isnull().sum()

user      0
isbn      0
rating    0
dtype: int64

In [ ]:
# Filter out users with less than 200 ratings
ratings_counts = df_ratings['user'].value_counts().sort_values(ascending=False)
ratings_counts.head()

11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: user, dtype: int64

In [ ]:
active_users = ratings_counts[ ratings_counts > 200].index
df_ratings_active = df_ratings[ df_ratings['user'].isin(active_users) ]
df_ratings_active.shape


(526356, 3)

In [ ]:
# Filter out books with less than 100 ratings
ratings_counts = df_ratings['isbn'].value_counts().sort_values(ascending=False)
ratings_counts.head()

0971880107    2502
0316666343    1295
0385504209     883
0060928336     732
0312195516     723
Name: isbn, dtype: int64

In [ ]:
popular_books = ratings_counts[ratings_counts > 100].index
df_ratings_active = df_ratings_active[ df_ratings_active['isbn'].isin(popular_books) ]
df_ratings_active.shape

(49254, 3)

In [ ]:
# Prepare a dataframe for training
df = pd.merge( df_ratings_active, df_books.set_index('isbn'), on='isbn')
df.head()

user        isbn  rating  \
0  277427  002542730X    10.0   
1    3363  002542730X     0.0   
2   11676  002542730X     6.0   
3   12538  002542730X    10.0   
4   13552  002542730X     0.0   

                                               title             author  
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner

In [ ]:
df = df.pivot_table(index='title', columns='user', values='rating').fillna(0)
df.sort_index()
df.head()

user                                                254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   

user                                                2977    3363    4017    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   

user                                                4385    6242    6251    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   

user                                                6323    ...  274004  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    0.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0  ...     0.0   

user                                                274061  274301  274308  \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   

user                                                274808  275970  277427  \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0   

user                                                277478  277639  278418  
title                                                                       
1984                                                   0.0     0.0     0.0  
1st to Die: A Novel                                    0.0     0.0     0.0  
2nd Chance                                             0.0     0.0     0.0  
4 Blondes                                              0.0     0.0     0.0  
A Beautiful Mind: The Life of Mathematical Geni...     0.0     0.0     0.0  

[5 rows x 882 columns]

In [ ]:
# Create a sparse matrix using csr_matrix
csr = csr_matrix(df.values)
csr.shape

(664, 882)

In [ ]:
# Create and train KNN model
model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(csr)

NearestNeighbors(algorithm='brute', metric='cosine')

In [ ]:
# Test the model
title = 'The Queen of the Damned (Vampire Chronicles (Paperback))'
df.loc[title].values

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  6., 10.,  0.,  0.,  0

In [ ]:
distance, index = model.kneighbors([df.loc[title].values], n_neighbors=6)
distance, index

(array([[5.9604645e-08, 5.1784116e-01, 5.2985442e-01, 7.3450685e-01,
         7.3627871e-01, 7.8334332e-01]], dtype=float32),
 array([[559, 602, 591, 250, 609, 274]]))

In [ ]:
df.iloc[index[0]].index.values

array(['The Queen of the Damned (Vampire Chronicles (Paperback))',
       'The Vampire Lestat (Vampire Chronicles, Book II)',
       'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
       'Interview with the Vampire',
       'The Witching Hour (Lives of the Mayfair Witches)',
       'Lasher: Lives of the Mayfair Witches (Lives of the Mayfair Witches)'],
      dtype=object)

In [ ]:
# function to return recommended books - this will be tested
def get_recommends(book_title, n_neighbors=6):
  book= df.loc[book_title]
  distance, index = model.kneighbors([book.values], n_neighbors=n_neighbors)
  books = pd.DataFrame({
      'title': df.iloc[ index[0] ].index.values,
      'distance': distance[0],
  })
  books = books.sort_values(by='distance', ascending=False).head(5).values
  return [book_title, books]

In [ ]:
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2):
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()

["Where the Heart Is (Oprah's Book Club (Paperback))", array([["I'll Be Seeing You", 0.8016210794448853],
       ['The Weight of Water', 0.7708583474159241],
       ['The Surgeon', 0.7699410915374756],
       ['I Know This Much Is True', 0.7677075266838074],
       ['The Lovely Bones: A Novel', 0.7230184078216553]], dtype=object)]
You passed the challenge! 🎉🎉🎉🎉🎉
